### ISSUE TITLE
Remix Support

### ISSUE THREAD

**Issue by chirdeeptomar** [meilisearch/meilisearch-react#35]
How do I get instant search working with Remix, is it possible with the current version?

**Comment by bidoubiwa** [comment]
I don't see why it couldn't work. It shouldn't be any different to implement than on a regular react project. At least for my understanding of remix.
Did you try it out? 

Here is an example of implementation: https://github.com/Haroenv/remix-plus-react-instantsearch.

Here: https://github.com/Haroenv/remix-plus-react-instantsearch/blob/main/app/routes/index.tsx you just need to use instantMeilisearch instead of `algoliasearch` and it should work.

**Comment by chirdeeptomar** [comment]
I figured it out, I had issue with process.env being used in client side code which was failing to load any javascript on the client.
