### ISSUE TITLE
Deduplicate requests with instantMeilisearch and instantsearch

### ISSUE THREAD

**Issue by chrissshh** [meilisearch/meilisearch-react#49]
Instantsearch sends multiple duplicate requests to fetch results when first loading the search page using instantMeilisearch and it seems to happen with this component using the useRefinementList hook. Instantsearch with algolia has an option to deduplicate requests using request cache but I can't find similar functionality with Meilisearch. 

Does anyone know how to fix this because I've tried just about everything. Thanks!!
```

function XRefinementList({
  attribute,
}: {
  attribute: string;
}) {
  const { items, refine } = useRefinementList({
    attribute: attribute,
    sortBy: ["count:desc", "name:asc"],
  });

  return (
    <div>
      {items.map((item) => (
        <div key={item.label}>
          <button
            type="button"
            onClick={() => {
              refine(item.value);
            }}
            disabled={item.count === 0}
          >
            {item.label}
          </button>
        </div>
      ))}
    </div>
  );
}
```

**Comment by curquiza** [comment]
Hey 

Looks like your issue is more related to a support need and not a request for feature or a bug fix.

You might have noticed when opening the issue we don't do support in this repo anymore.

<img width="1230" alt="Capture d’écran 2023-10-11 à 16 56 38" src="https://github.com/meilisearch/meilisearch-java/assets/20380692/d32e8d6f-9bb3-4bdb-89fd-85ebb4572f0f">


We are a small team, so we can’t spend much time doing support this specific repo  anymore :cry:

I would recommend going to our [Discord](https://discord.gg/meilisearch) instead. The community will be able to help you, no matter your question.

Thanks for using Meilisearch!
